<?php
include 'header.php';
include 'inc.php';
?>
<div class="navbar"style="background-color:green;box-shadow: 4px 10px 15px grey;">
	<?php include 'navbar.php'; ?>
</div>
<div class="container">
<div class="row">
	
	<div class="col-sm-12">
		<div class="well"style="box-shadow: 4px 10px 15px grey;">
		
		<?php
		if(isset($_GET['buy']))
		{
			include 'buy.php';
		}else if(isset($_GET['sell'])){
			include 'sell.php';
		}else if(isset($_GET['view'])){
			include 'view.php';
		}else if(isset($_GET['previous'])){
			include 'previous.php';

		}
		else if(isset($_GET['product_idd']) && isset($_GET['username'])){
			$id=$_GET['product_idd'];
			$buyer=$_GET['username'];
			$select="SELECT * FROM products WHERE product_id='$id'";
			$query=mysqli_query($connect,$select);
			$array=mysqli_fetch_array($query,MYSQLI_ASSOC);
			$desc=$array['product_desc'];
			$product_type="MERCHANT";
			$product_price=$array['product_price'];
			$prod_reference=rand();
			$se="SELECT * FROM users_table WHERE email='$buyer'";
			$que=mysqli_query($connect,$se);
			$arr=mysqli_fetch_array($que,MYSQLI_ASSOC);
			$firstname=$arr['fname'];
			$lastname=$arr['lname'];
			$phoneno=$arr['mobile'];
		   
			$insert="INSERT INTO payments(product_id,buyer,amount,reference,status)VALUES('$id','$buyer','	$product_price','$prod_reference','Pending')";
			
		   
			if($www=mysqli_query($connect,$insert)){
				
	
	include_once('OAuth.php');

	//pesapal params
	$token = $params = NULL;
	
	/*
	PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
	when you are ready to go live change to https://www.pesapal.com.
	*/
	$consumer_key = 'ZAsAEeXxcOtCmsxVZfA6VSm7ODZaQI2Y';//Register a merchant account on
					   //demo.pesapal.com and use the merchant key for testing.
					   //When you are ready to go live make sure you change the key to the live account
					   //registered on www.pesapal.com!
	$consumer_secret = 'bypw/6l7bmzAIbH6j+qN7YPHZkM=';// Use the secret from your test
					   //account on demo.pesapal.com. When you are ready to go live make sure you 
					   //change the secret to the live account registered on www.pesapal.com!
	$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
	$iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
					   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
	
	//get form details
	$amount = $product_price;
	$amount = number_format($amount, 2);//format amount to 2 decimal places
	
	$desc = $desc;
	$type = "MERCHANT"; //default value = MERCHANT
	$reference = $prod_reference;//unique order id of the transaction, generated by merchant
	$first_name = $firstname;
	$last_name = $lastname;
	$email = $user;
	$phonenumber = $phoneno;//ONE of email or phonenumber is required
	
	$callback_url = 'http://localhost/eshamba/callback.php'; //redirect url, the page that will handle the response from pesapal.
	
	$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
	$post_xml = htmlentities($post_xml);
	
	$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
	
	//post transaction to pesapal
	$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
	$iframe_src->set_parameter("oauth_callback", $callback_url);
	$iframe_src->set_parameter("pesapal_request_data", $post_xml);
	$iframe_src->sign_request($signature_method, $consumer, $token);
	
	//display pesapal - iframe and pass iframe_src
	?>
	<iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
		<p>Browser unable to load iFrame</p>
	</iframe>
	<?php
	}
	?>
		   













		
<?php
		}
	
		
		else if(!isset($_GET['buy'])&& !isset($_GET['sell']) && !isset($_GET['view']) && !isset($_GET['product_idd'])&& !isset($_GET['username']) && !isset($_GET['previous']))
		{
			include 'sell.php';
		}
		?>
		</div><!--end of well-->
	</div><!--end of col-->
</div><!--End of row-->
</div><!--End of container-->
<?php 
include 'footer.php';
?>